# Do not edit this file


# Debug display
$execute if score .kf_3d_triggers.debug kf_3d_triggers matches 1 positioned 0 0 0 positioned $(x) $(y) $(z) if entity @a[dx=$(dx),dy=$(dy),dz=$(dz)] run title @a actionbar {"color":"green","text":"TRIGGERED!"}
$execute if score .kf_3d_triggers.debug kf_3d_triggers matches 1 positioned 0 0 0 positioned $(x) $(y) $(z) unless entity @a[dx=$(dx),dy=$(dy),dz=$(dz)] run title @a actionbar {"color":"red","text":"TRIGGERED!"}

# Display triggers anchor
$execute if score .kf_3d_triggers.debug kf_3d_triggers matches 1 positioned 0 0 0 positioned $(x) $(y) $(z) run particle bubble ~ ~ ~ 0.01 0.01 0.01 0 1 force @a

# Display stained glass if debug is on
$execute if score .kf_3d_triggers.debug kf_3d_triggers matches 1 unless entity @e[tag=kf.$(id).trigger] run function kf_3d_triggers:private/summon_display with storage kf_3d_triggers $(id)
execute if score .kf_3d_triggers.debug kf_3d_triggers matches 0 run kill @e[tag=kf.trigger]

# Display the name
$data merge entity @n[type=block_display,tag=kf.$(id).trigger] {CustomNameVisible:1b,CustomName:"Trigger: [$(id)]",block_state:{Name:"minecraft:red_stained_glass"}}

# Check if entity is inside of the dx dy dz
$execute if score .kf_3d_triggers.$(id).single kf_3d_triggers matches 0 positioned 0 0 0 positioned $(x) $(y) $(z) as $(selector) if entity @s[dx=$(dx),dy=$(dy),dz=$(dz)] run $(command)

# Check if entity is inside of the dx dy dz + single use
$execute if score .kf_3d_triggers.$(id).single kf_3d_triggers matches 1 if score .kf_3d_triggers.$(id).triggered kf_3d_triggers matches 0 positioned 0 0 0 positioned $(x) $(y) $(z) as $(selector) if entity @s[dx=$(dx),dy=$(dy),dz=$(dz)] run function kf_3d_triggers:private/redirect with storage kf_3d_triggers $(id)

# Tp block_display to the anchor
$execute positioned 0 0 0 positioned $(x) $(y) $(z) run tp @n[tag=kf.$(id).trigger] ~ ~ ~

# Moving the anchor to the player
execute if score .kf_3d_triggers.move kf_3d_triggers matches 1 store result score .kf_tempX kf_3d_triggers run data get entity @n[type=player] Pos[0] 100
execute if score .kf_3d_triggers.move kf_3d_triggers matches 1 store result score .kf_tempY kf_3d_triggers run data get entity @n[type=player] Pos[1] 100
execute if score .kf_3d_triggers.move kf_3d_triggers matches 1 store result score .kf_tempZ kf_3d_triggers run data get entity @n[type=player] Pos[2] 100

$execute if score .kf_3d_triggers.move kf_3d_triggers matches 1 store result storage kf_3d_triggers $(id).x double 0.01 run scoreboard players get .kf_tempX kf_3d_triggers
$execute if score .kf_3d_triggers.move kf_3d_triggers matches 1 store result storage kf_3d_triggers $(id).y double 0.01 run scoreboard players get .kf_tempY kf_3d_triggers
$execute if score .kf_3d_triggers.move kf_3d_triggers matches 1 store result storage kf_3d_triggers $(id).z double 0.01 run scoreboard players get .kf_tempZ kf_3d_triggers

scoreboard players reset .kf_tempX kf_3d_triggers
scoreboard players reset .kf_tempY kf_3d_triggers
scoreboard players reset .kf_tempZ kf_3d_triggers