# Do not edit this file.


$data modify storage kf_quicksaves $(node).data[$(id)].score set value "$(score)"
$data modify storage kf_quicksaves $(node).data[$(id)].obj set value "$(obj)"
$data modify storage kf_quicksaves $(node).data[$(id)].value set value $(value)

$execute store result score #quicksave_temp kf_quicksave run data get storage kf_quicksaves $(node).id
scoreboard players add #quicksave_temp kf_quicksave 1
$execute store result storage kf_quicksaves $(node).id int 1 run scoreboard players get #quicksave_temp kf_quicksave