# Do not edit this file.


$data modify storage kf_quicksaves input.score set from storage kf_quicksaves $(active_node).data[$(active_id)].score
$data modify storage kf_quicksaves input.value set from storage kf_quicksaves $(active_node).data[$(active_id)].value
$data modify storage kf_quicksaves input.obj set from storage kf_quicksaves $(active_node).data[$(active_id)].obj

$scoreboard players set $(score) $(obj) $(value)

scoreboard players add #quicksave_id kf_quicksave 1
execute store result storage kf_quicksaves input.active_id int 1 run scoreboard players get #quicksave_id kf_quicksave

execute unless score #quicksave_id kf_quicksave matches 11.. run function kf_quicksave:private/iterator with storage kf_quicksaves input