# Do not edit this file.


$data modify storage kf_quicksaves input.active_node set value $(node)
$data modify storage kf_quicksaves input.score set from storage kf_quicksaves $(node).data[0].score
$data modify storage kf_quicksaves input.value set from storage kf_quicksaves $(node).data[0].value
$data modify storage kf_quicksaves input.obj set from storage kf_quicksaves $(node).data[0].obj

scoreboard players set #quicksave_id kf_quicksave 1
execute store result storage kf_quicksaves input.active_id int 1 run scoreboard players get #quicksave_id kf_quicksave
function kf_quicksave:private/iterator with storage kf_quicksaves input