# Do not edit this file.


$execute store result storage kf_quicksaves input.id int 1 run data get storage kf_quicksaves $(node).id
$execute store result storage kf_quicksaves input.value int 1 run scoreboard players get $(score) $(obj)

$data modify storage kf_quicksaves input.node set value "$(node)"
$data modify storage kf_quicksaves input.score set value "$(score)"
$data modify storage kf_quicksaves input.obj set value "$(obj)"

function kf_quicksave:private/import with storage kf_quicksaves input