# Do not edit this file.


$data modify storage kf_quicksaves $(node).data[$(id)].score set value ""
$data modify storage kf_quicksaves $(node).data[$(id)].obj set value ""
$data modify storage kf_quicksaves $(node).data[$(id)].value set value 0