# Do not edit this file.


$data modify storage kf_quicksaves $(node).data[$(id)].score set value $(score)
$data modify storage kf_quicksaves $(node).data[$(id)].obj set value $(obj)
$execute store result storage kf_quicksaves $(node).data[$(id)].value int 1 run scoreboard players get $(score) $(obj)