# Do not edit this file.


# Redirecting with the selected preseta
$data modify storage dialogue_presets $(name).text set value "$(text)"
$data modify storage dialogue_presets $(name).node set value "$(node)"

$function modules:dialogue/create with storage dialogue_presets $(name)

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Dialogue]: ","color":"green","bold":false},{"text":"Created node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false},{"text":"with preset: ","color":"gold","bold":false},{"text":"$(name)","color":"yellow","bold":false}]}