# Do not edit this file.


# Create score base
scoreboard objectives add dialogues dummy

# Creating a dialogue storage
$data merge storage dialogue {$(node):{text:"$(text)",author:$(author),step:$(step),selector:"$(selector)",display:$(display),id:"$(node)",len:0,char:$(step),command:"$(command)",delay:$(delay),stay:$(stay)}}
$data modify storage dialogue node_list.data append value $(node)

# Getting the text's length and storing it
$execute store result score dialogue.$(node).len dialogues run data get storage dialogue $(node).text
$execute store result storage dialogue $(node).len int 1 run scoreboard players get dialogue.$(node).len dialogues

# Getting the delayed timer
$execute store result score dialogue.$(node).stay dialogues run data get storage dialogue $(node).stay

# Setting up the display.text with the first (or a couple of, depending on step) symbols
$data modify storage minecraft:dialogue $(node).display.text set string storage minecraft:dialogue $(node).text 0 $(step)

# Setting up delay timer
$scoreboard players set dialogue.$(node).delay dialogues 0

# Setting up run score
$scoreboard players set dialogue.$(node).run dialogues 1

# Setting up char counter
$scoreboard players set dialogue.$(node).char dialogues $(step)

# Checking if text length is bigger than step value. If not - change step to 1
$scoreboard players set dialogue.$(node).step dialogues $(step)
$execute if score dialogue.$(node).step dialogues > dialogue.$(node).len dialogues run data modify storage dialogue $(node).step set value 1
$execute if score dialogue.$(node).step dialogues > dialogue.$(node).len dialogues run data modify storage dialogue $(node).display.text set string storage minecraft:dialogue $(node).text 0 1
$execute store result score dialogue.$(node).step dialogues run data get storage dialogue $(node).step 1

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Dialogue]: ","color":"green","bold":false},{"text":"Created node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}