# Do not edit this file.


# Creating the preset
$data merge storage dialogue_presets {$(name):{author:$(author),step:$(step),selector:"$(selector)",display:$(display),char:$(step),command:"$(command)",delay:$(delay),stay:$(stay)}}
$data modify storage dialogue_presets node_list.data append value $(name)

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Dialogue]: ","color":"green","bold":false},{"text":"Created preset: ","color":"gold","bold":false},{"text":"$(name) ","color":"yellow","bold":false}]}