# Do not edit this file.


# Pulling the dialogue node data from the first index
data modify storage dialogue node_list.value set from storage dialogue node_list.data[0]

# Setting the dialogue node id
scoreboard players set dialogues.node_list.id dialogues 1
execute store result storage dialogue node_list.active_id int 1 run scoreboard players get dialogues.node_list.id dialogues

# Pulling the dialogue size
execute store result score dialogues.node_list.size dialogues run data get storage dialogue node_list.data

# Dev mode debug
execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Dialogue]: ","color":"green","bold":false},{"text":"Deleted all nodes: ","color":"gold","bold":false},{"color":"yellow","bold":false,"score":{"name":"dialogues.node_list.size","objective":"dialogues"}}]}

scoreboard players add dialogues.node_list.size dialogues 1

# Starting the recursive iterator function
function modules:dialogue/private/_delete_all_nodes with storage dialogue node_list