# Do not edit this file.


# Deleting all the data connected to the dialogue
$data remove storage dialogue $(node)
$scoreboard players reset dialogue.$(node).len
$scoreboard players reset dialogue.$(node).step
$scoreboard players reset dialogue.$(node).char
$scoreboard players reset dialogue.$(node).delay
$scoreboard players reset dialogue.$(node).stay
$scoreboard players reset dialogue.$(node).run

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Dialogue]: ","color":"green","bold":false},{"text":"Deleted node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}