# Do not edit this file.


# Removing all the data
$data remove storage dialogue_queues $(name)
$scoreboard players reset dialogue.$(name).queue_len dialogues.queue
$scoreboard players reset dialogue.$(name).queue_index dialogues.queue

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Dialogue]: ","color":"green","bold":false},{"text":"Deleted queue: ","color":"gold","bold":false},{"text":"$(name) ","color":"yellow","bold":false}]}