# Do not edit this file.


$function modules:dialogue/private/_reset with storage dialogue $(node)

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Dialogue]: ","color":"green","bold":false},{"text":"Reset node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}