# Do not edit this file.


# Creating on_start scoreboards to reset them
scoreboard objectives remove KFrame.load
scoreboard objectives add KFrame.load minecraft.custom:minecraft.leave_game
scoreboard players set #KF_ON_START_LOCK KFrame 0