# Do not edit this file.


# Toggle inputs on_load and on_tick functions | 0/1
execute if score #KF_INPUTS_TOGGLE KFrame matches 0 run return run scoreboard players set #KF_INPUTS_TOGGLE KFrame 1
execute if score #KF_INPUTS_TOGGLE KFrame matches 1 run return run scoreboard players set #KF_INPUTS_TOGGLE KFrame 0