# Do not edit this file.


# Creating timers main scoreboard
scoreboard objectives add timers dummy

# Creating a timers storage
$data merge storage timers {$(node):{id:$(node),t:$(t),h:$(h),m:$(m),s:$(s),end_h:$(end_h),end_m:$(end_m),end_s:$(end_s),end_t:$(end_t),single:$(single),command:"$(command)",init:[{t:$(t),h:$(h),m:$(m),s:$(s),end_h:$(end_h),end_m:$(end_m),end_s:$(end_s)}]}}
$data modify storage timers node_list.data append value $(node)

# Saving all the data in the scoreboards
$execute store result score timers.$(node).t timers run data get storage timers $(node).t
$execute store result score timers.$(node).single timers run data get storage timers $(node).single
$execute store result score timers.$(node).h timers run data get storage timers $(node).h
$execute store result score timers.$(node).m timers run data get storage timers $(node).m
$execute store result score timers.$(node).s timers run data get storage timers $(node).s
$execute store result score timers.$(node).end_h timers run data get storage timers $(node).end_h
$execute store result score timers.$(node).end_m timers run data get storage timers $(node).end_m
$execute store result score timers.$(node).end_s timers run data get storage timers $(node).end_s
$execute store result score timers.$(node).end_t timers run data get storage timers $(node).end_t

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Timers]: ","color":"green","bold":false},{"text":"Created node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}