# Do not edit this file.


# Pulling the dialogue node data from the first index
data modify storage timers node_list.value set from storage timers node_list.data[0]

# Setting the dialogue node id
scoreboard players set timers.node_list.id dialogues 1
execute store result storage timers node_list.active_id int 1 run scoreboard players get timers.node_list.id timers

# Pulling the dialogue size
execute store result score timers.node_list.size timers run data get storage timers node_list.data

# Dev mode debug
execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Timers]: ","color":"green","bold":false},{"text":"Deleted all nodes: ","color":"gold","bold":false},{"color":"yellow","bold":false,"score":{"name":"timers.node_list.size","objective":"timers"}}]}

scoreboard players add timers.node_list.size timers 1

# Starting the recursive iterator function
function modules:timers/private/_delete_all with storage timers node_list