# Do not edit this file.


# Deleting data and scoreboard tied to the timer
$data remove storage timers $(node)
$scoreboard players reset timers.$(node).single timers
$scoreboard players reset timers.$(node).t timers
$scoreboard players reset timers.$(node).h timers
$scoreboard players reset timers.$(node).m timers
$scoreboard players reset timers.$(node).s timers
$scoreboard players reset timers.$(node).end_h timers
$scoreboard players reset timers.$(node).end_m timers
$scoreboard players reset timers.$(node).end_s timers
$scoreboard players reset timers.$(node).end_t timers

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Timers]: ","color":"green","bold":false},{"text":"Deleted node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}