# Do not edit this file.


# If timers runs to its point - execute the command
$execute if score timers.$(node).t timers = timers.$(node).end_t timers if score timers.$(node).s timers = timers.$(node).end_s timers if score timers.$(node).m timers = timers.$(node).end_m timers if score timers.$(node).h timers = timers.$(node).end_h timers run function modules:timers/private/_execute with storage timers $(node)

# Iteration process
$execute if score timers.$(node).t timers matches 0.. if score timers.$(node).single timers matches 0 unless score timers.$(node).s timers = timers.$(node).end_s timers run scoreboard players add timers.$(node).t timers 1
$execute if score timers.$(node).t timers matches 0.. if score timers.$(node).single timers matches 0 unless score timers.$(node).m timers = timers.$(node).end_m timers run scoreboard players add timers.$(node).t timers 1
$execute if score timers.$(node).t timers matches 0.. if score timers.$(node).single timers matches 0 unless score timers.$(node).h timers = timers.$(node).end_h timers run scoreboard players add timers.$(node).t timers 1
$execute if score timers.$(node).t timers matches 0.. if score timers.$(node).single timers matches 1.. run scoreboard players add timers.$(node).t timers 1

# Incrementings values
$execute if score timers.$(node).t timers matches 20.. run function modules:timers/private/_increment_s with storage timers $(node)
$execute if score timers.$(node).s timers matches 60.. run function modules:timers/private/_increment_m with storage timers $(node)
$execute if score timers.$(node).m timers matches 60.. run function modules:timers/private/_increment_h with storage timers $(node)

# Storing them back in data
$execute store result storage timers $(node).h int 1 run scoreboard players get timers.$(node).h timers
$execute store result storage timers $(node).m int 1 run scoreboard players get timers.$(node).m timers
$execute store result storage timers $(node).s int 1 run scoreboard players get timers.$(node).s timers
$execute store result storage timers $(node).t int 1 run scoreboard players get timers.$(node).t timers