# Do not edit this file.


# Pull data from the init path to the original path
$data modify storage timers $(node).t set from storage timers $(node).init.[].t
$data modify storage timers $(node).s set from storage timers $(node).init.[].s
$data modify storage timers $(node).m set from storage timers $(node).init.[].m
$data modify storage timers $(node).h set from storage timers $(node).init.[].h
$data modify storage timers $(node).end_s set from storage timers $(node).init.[].end_s
$data modify storage timers $(node).end_m set from storage timers $(node).init.[].end_m
$data modify storage timers $(node).end_h set from storage timers $(node).init.[].end_h

$execute store result score timers.$(node).t timers run data get storage timers $(node).t
$execute store result score timers.$(node).h timers run data get storage timers $(node).h
$execute store result score timers.$(node).m timers run data get storage timers $(node).m
$execute store result score timers.$(node).s timers run data get storage timers $(node).s
$execute store result score timers.$(node).end_h timers run data get storage timers $(node).end_h
$execute store result score timers.$(node).end_m timers run data get storage timers $(node).end_m
$execute store result score timers.$(node).end_s timers run data get storage timers $(node).end_s

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Timers]: ","color":"green","bold":false},{"text":"Reset node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}