# Do not edit this file.


$function modules:timers/private/_set_$(arg) {id:$(node),value:"$(value)"}

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Timers]: ","color":"green","bold":false},{"text":"Set node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false},{"text":"with arg: ","color":"gold","bold":false},{"text":"$(arg) ","color":"yellow","bold":false},{"text":"with value: ","color":"gold","bold":false},{"text":"$(value) ","color":"light_purple","bold":false}]}