# Do not edit this file.


# Creating KFrame scores, on_start base scoreboard
scoreboard objectives add KFrame dummy
scoreboard objectives add KFrame.load minecraft.custom:minecraft.leave_game

# Turning on all necessary namespaces
function main:on_load