# Do not edit this file.


# Unlocking inputs for the current player via arg
# Acceptable args: all, w, a, s, d, space, shift, ctrl, slot1, slot2, slot3, slot4, slot5, slot6, slot7, slot8, slot9
$function modules:inputs/private/unlock/_$(arg)