# Do not edit this file.


# Operator function for deleting all input scoreboards
scoreboard objectives remove inputs.w_lock
scoreboard objectives remove inputs.a_lock
scoreboard objectives remove inputs.s_lock
scoreboard objectives remove inputs.d_lock
scoreboard objectives remove inputs.ctrl_lock
scoreboard objectives remove inputs.shift_lock
scoreboard objectives remove inputs.space_lock

scoreboard objectives remove inputs.slot1_lock
scoreboard objectives remove inputs.slot2_lock
scoreboard objectives remove inputs.slot3_lock
scoreboard objectives remove inputs.slot4_lock
scoreboard objectives remove inputs.slot5_lock
scoreboard objectives remove inputs.slot6_lock
scoreboard objectives remove inputs.slot7_lock
scoreboard objectives remove inputs.slot8_lock
scoreboard objectives remove inputs.slot9_lock

scoreboard objectives remove inputs.w_trigger
scoreboard objectives remove inputs.a_trigger
scoreboard objectives remove inputs.s_trigger
scoreboard objectives remove inputs.d_trigger
scoreboard objectives remove inputs.ctrl_trigger
scoreboard objectives remove inputs.shift_trigger
scoreboard objectives remove inputs.space_trigger

scoreboard objectives remove inputs.slot1_trigger
scoreboard objectives remove inputs.slot2_trigger
scoreboard objectives remove inputs.slot3_trigger
scoreboard objectives remove inputs.slot4_trigger
scoreboard objectives remove inputs.slot5_trigger
scoreboard objectives remove inputs.slot6_trigger
scoreboard objectives remove inputs.slot7_trigger
scoreboard objectives remove inputs.slot8_trigger
scoreboard objectives remove inputs.slot9_trigger