# Do not edit this file.


# Creating all the input scoreboards
scoreboard objectives add inputs.w_lock dummy
scoreboard objectives add inputs.a_lock dummy
scoreboard objectives add inputs.s_lock dummy
scoreboard objectives add inputs.d_lock dummy
scoreboard objectives add inputs.ctrl_lock dummy
scoreboard objectives add inputs.shift_lock dummy
scoreboard objectives add inputs.space_lock dummy

scoreboard objectives add inputs.slot1_lock dummy
scoreboard objectives add inputs.slot2_lock dummy
scoreboard objectives add inputs.slot3_lock dummy
scoreboard objectives add inputs.slot4_lock dummy
scoreboard objectives add inputs.slot5_lock dummy
scoreboard objectives add inputs.slot6_lock dummy
scoreboard objectives add inputs.slot7_lock dummy
scoreboard objectives add inputs.slot8_lock dummy
scoreboard objectives add inputs.slot9_lock dummy

scoreboard objectives add inputs.w_trigger dummy
scoreboard objectives add inputs.a_trigger dummy
scoreboard objectives add inputs.s_trigger dummy
scoreboard objectives add inputs.d_trigger dummy
scoreboard objectives add inputs.ctrl_trigger dummy
scoreboard objectives add inputs.shift_trigger dummy
scoreboard objectives add inputs.space_trigger dummy

scoreboard objectives add inputs.slot1_trigger dummy
scoreboard objectives add inputs.slot2_trigger dummy
scoreboard objectives add inputs.slot3_trigger dummy
scoreboard objectives add inputs.slot4_trigger dummy
scoreboard objectives add inputs.slot5_trigger dummy
scoreboard objectives add inputs.slot6_trigger dummy
scoreboard objectives add inputs.slot7_trigger dummy
scoreboard objectives add inputs.slot8_trigger dummy
scoreboard objectives add inputs.slot9_trigger dummy