# Do not edit this file.


# Printing the actionbar with all the inputs
$title @s actionbar [{"color":"$(w)","text":"W"},{"color":"$(a)","text":"A"},{"color":"$(s)","text":"S"},{"color":"$(d)","text":"D"},{"color":"white","text":" | "},{"color":"$(ctrl)","text":"CTRL"},{"color":"$(shift)","text":" SHIFT"},{"color":"$(space)","text":" SPACE"},{"color":"white","text":" | "},{"color":"$(slot1)","text":"1"},{"color":"$(slot2)","text":" 2"},{"color":"$(slot3)","text":" 3"},{"color":"$(slot4)","text":" 4"},{"color":"$(slot5)","text":" 5"},{"color":"$(slot6)","text":" 6"},{"color":"$(slot7)","text":" 7"},{"color":"$(slot8)","text":" 8"},{"color":"$(slot9)","text":" 9"}]