# Do not edit this file.


# Resetting all input scoreboards for all players to reset trigger/single functions
execute unless entity @s[predicate=modules:inputs/w_input] run scoreboard players set @s inputs.w_trigger 0
execute unless entity @s[predicate=modules:inputs/a_input] run scoreboard players set @s inputs.a_trigger 0
execute unless entity @s[predicate=modules:inputs/s_input] run scoreboard players set @s inputs.s_trigger 0
execute unless entity @s[predicate=modules:inputs/d_input] run scoreboard players set @s inputs.d_trigger 0
execute unless entity @s[predicate=modules:inputs/sprint_input] run scoreboard players set @s inputs.ctrl_trigger 0
execute unless entity @s[predicate=modules:inputs/shift_input] run scoreboard players set @s inputs.shift_trigger 0
execute unless entity @s[predicate=modules:inputs/space_input] run scoreboard players set @s inputs.space_trigger 0

execute unless entity @s[predicate=modules:inputs/slot0] run scoreboard players set @s inputs.slot1_trigger 0
execute unless entity @s[predicate=modules:inputs/slot1] run scoreboard players set @s inputs.slot2_trigger 0
execute unless entity @s[predicate=modules:inputs/slot2] run scoreboard players set @s inputs.slot3_trigger 0
execute unless entity @s[predicate=modules:inputs/slot3] run scoreboard players set @s inputs.slot4_trigger 0
execute unless entity @s[predicate=modules:inputs/slot4] run scoreboard players set @s inputs.slot5_trigger 0
execute unless entity @s[predicate=modules:inputs/slot5] run scoreboard players set @s inputs.slot6_trigger 0
execute unless entity @s[predicate=modules:inputs/slot6] run scoreboard players set @s inputs.slot7_trigger 0
execute unless entity @s[predicate=modules:inputs/slot7] run scoreboard players set @s inputs.slot8_trigger 0
execute unless entity @s[predicate=modules:inputs/slot8] run scoreboard players set @s inputs.slot9_trigger 0