# Do not edit this file.


# Creating timers main scoreboard
scoreboard objectives add timers dummy

# Creating a timers storage
$data merge storage timers {$(node):{id:$(node),t:$(t),h:$(h),m:$(m),s:$(s),end_h:$(end_h),end_m:$(end_m),end_s:$(end_s),end_t:$(end_t),single:$(single),command:"$(command)",init:[{t:$(t),h:$(h),m:$(m),s:$(s),end_h:$(end_h),end_m:$(end_m),end_s:$(end_s)}]}}

# Saving all the data in the scoreboards
$execute store result score .timers.$(node).tick timers run data get storage timers $(node).t
$execute store result score .timers.$(node).single timers run data get storage timers $(node).single
$execute store result score .timers.$(node).h timers run data get storage timers $(node).h
$execute store result score .timers.$(node).m timers run data get storage timers $(node).m
$execute store result score .timers.$(node).s timers run data get storage timers $(node).s
$execute store result score .timers.$(node).end_h timers run data get storage timers $(node).end_h
$execute store result score .timers.$(node).end_m timers run data get storage timers $(node).end_m
$execute store result score .timers.$(node).end_s timers run data get storage timers $(node).end_s
$execute store result score .timers.$(node).end_t timers run data get storage timers $(node).end_t