# Do not edit this file.


# Recursively creating the size of the quicksave node
$data modify storage minecraft:quicksaves $(id).data append value {score:"",obj:"",value:0}
$scoreboard players add quicksave.$(id).temp quicksave 1

# If the temporary size is less than the quicksave size, continue creating the size
$execute if score quicksave.$(id).temp quicksave < quicksave.$(id).size quicksave run function modules:quicksave/private/_add_size with storage quicksaves $(id)

# If the temporary size is equal to the quicksave size, clear the temporary data
$execute if score quicksave.$(id).temp quicksave = quicksave.$(id).size quicksave run function modules:quicksave/private/_clear_temp with storage quicksaves $(id)