# Do not edit this file.


# Appending data to the quicksave node
$data modify storage minecraft:quicksaves $(id).data[$(temp)].score set value "$(score)"
$data modify storage minecraft:quicksaves $(id).data[$(temp)].obj set value "$(obj)"
$data modify storage minecraft:quicksaves $(id).data[$(temp)].value set value $(value)
