# Do not edit this file.


# Checking if the quicksave node.obj is not null
$execute store result score quicksave.$(id).temp1 quicksave run data get storage minecraft:quicksaves $(id).data[$(temp)].obj

# If the quicksave node.obj is not null, append the data
$execute if score quicksave.$(id).temp1 quicksave matches ..0 run function modules:quicksave/private/_append with storage quicksaves $(id).input
$execute if score quicksave.$(id).temp1 quicksave matches ..0 run function modules:quicksave/private/_clear_temp with storage quicksaves $(id)

# If the quicksave node.obj is not null, increment the temp scoreboard
$execute store result score quicksave.$(id).temp quicksave run data get storage minecraft:quicksaves $(id).input.temp
$scoreboard players add quicksave.$(id).temp quicksave 1
$execute store result storage quicksaves $(id).input.temp int 1 run scoreboard players get quicksave.$(id).temp quicksave
$scoreboard players reset quicksave.$(id).temp quicksave

# If the quicksave node.obj is not null, run the recursive function
$function modules:quicksave/private/_check_data with storage quicksaves $(id).input