# Do not edit this file.


# Clearing temporary data after the size is created
$scoreboard players reset quicksave.$(id).temp quicksave
$scoreboard players reset quicksave.$(id).temp1 quicksave
$scoreboard players reset quicksave.$(id).size quicksave
$scoreboard players reset quicksave.$(id).id quicksave
$scoreboard players reset quicksave.$(id).print.id quicksave
scoreboard players reset quicksave.node_list.id quicksave
scoreboard players reset quicksave.node_list.size quicksave
$data remove storage quicksaves $(id).size
$data remove storage quicksaves $(id).input