# Do not edit this file.


# Setting the scoreboard with the pulled data
$scoreboard players set $(score) $(obj) $(value)

# Pulling the quicksave data from the storage
$data modify storage quicksaves $(active_node).input.score set from storage quicksaves $(active_node).data[$(active_id)].score
$data modify storage quicksaves $(active_node).input.value set from storage quicksaves $(active_node).data[$(active_id)].value
$data modify storage quicksaves $(active_node).input.obj set from storage quicksaves $(active_node).data[$(active_id)].obj

# Incrementing the quicksave ID
$scoreboard players add quicksave.$(active_node).id quicksave 1
$execute store result storage quicksaves $(active_node).input.active_id int 1 run scoreboard players get quicksave.$(active_node).id quicksave

# If the quicksave is not iterated through, run the function again
$execute unless score quicksave.$(active_node).id quicksave >= quicksave.$(active_node).size quicksave run function modules:quicksave/private/_iterator with storage quicksaves $(active_node).input

# If the quicksave is iterated through fully, delete the temporary data
$execute if score quicksave.$(active_node).id quicksave = quicksave.$(active_node).size quicksave run function modules:quicksave/private/_clear_temp with storage quicksaves $(active_node)