# Do not edit this file.


# If ANY input is triggered, and the input is unlocked - return 1
execute if entity @s[predicate=modules:inputs/w_input,scores={inputs.w_lock=0,inputs.w_trigger=0}] run return run scoreboard players set @s inputs.w_trigger 1
execute if entity @s[predicate=modules:inputs/a_input,scores={inputs.a_lock=0,inputs.a_trigger=0}] run return run scoreboard players set @s inputs.a_trigger 1
execute if entity @s[predicate=modules:inputs/s_input,scores={inputs.s_lock=0,inputs.s_trigger=0}] run return run scoreboard players set @s inputs.s_trigger 1
execute if entity @s[predicate=modules:inputs/d_input,scores={inputs.d_lock=0,inputs.d_trigger=0}] run return run scoreboard players set @s inputs.d_trigger 1
execute if entity @s[predicate=modules:inputs/sprint_input,scores={inputs.ctrl_lock=0,inputs.ctrl_trigger=0}] run return run scoreboard players set @s inputs.ctrl_trigger 1
execute if entity @s[predicate=modules:inputs/shift_input,scores={inputs.shift_lock=0,inputs.shift_trigger=0}] run return run scoreboard players set @s inputs.shift_trigger 1
execute if entity @s[predicate=modules:inputs/space_input,scores={inputs.space_lock=0,inputs.space_trigger=0}] run return run scoreboard players set @s inputs.space_trigger 1