# Do not edit this file.


# Delete all the copies
$function modules:3d_triggers/delete {node:$(node)}

# Create score base
scoreboard objectives add 3d_triggers dummy

# Creating the storage
$data merge storage 3d_triggers {$(node):{id:$(node),x:$(x)d,y:$(y)d,z:$(z)d,dx:$(dx),dy:$(dy),dz:$(dz),command:"$(command)",single:$(single),selector:"$(selector)",offset_x:0.0,offset_y:0.0,offset_z:0.0,color:$(color)}}
$data modify storage 3d_triggers node_list.data append value $(node)

# Getting the "single" arg
$execute store result score 3d_triggers.$(node).single 3d_triggers run data get storage 3d_triggers $(node).single

# Setting the triggered value to zero for single uses
$scoreboard players set 3d_triggers.$(node).triggered 3d_triggers 0

# Pulling dx dy dz from storage
$execute store result score 3d_triggers.$(node).temp1 3d_triggers run data get storage 3d_triggers $(node).dx 100
$execute store result score 3d_triggers.$(node).temp2 3d_triggers run data get storage 3d_triggers $(node).dy 100
$execute store result score 3d_triggers.$(node).temp3 3d_triggers run data get storage 3d_triggers $(node).dz 100

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [3D Triggers]: ","color":"green","bold":false},{"text":"Created node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}

# Checking if the trigger is small or big
$execute if score 3d_triggers.$(node).temp1 3d_triggers matches ..99 run return run function modules:3d_triggers/private/_create_small with storage 3d_triggers $(node)
$execute if score 3d_triggers.$(node).temp2 3d_triggers matches ..99 run return run function modules:3d_triggers/private/_create_small with storage 3d_triggers $(node)
$execute if score 3d_triggers.$(node).temp3 3d_triggers matches ..99 run return run function modules:3d_triggers/private/_create_small with storage 3d_triggers $(node)

$execute if score 3d_triggers.$(node).temp1 3d_triggers matches 99.. run return run function modules:3d_triggers/private/_create_big with storage 3d_triggers $(node)
$execute if score 3d_triggers.$(node).temp2 3d_triggers matches 99.. run return run function modules:3d_triggers/private/_create_big with storage 3d_triggers $(node)
$execute if score 3d_triggers.$(node).temp3 3d_triggers matches 99.. run return run function modules:3d_triggers/private/_create_big with storage 3d_triggers $(node)