# Do not edit this file.


# Kill the entities connected to the trigger node
$kill @e[tag=3d_triggers.$(node)]
$kill @e[tag=3d_triggers.$(node).display]

# Reset scores related to the trigger node
$scoreboard players reset 3d_triggers.$(node).single 3d_triggers
$scoreboard players reset 3d_triggers.$(node).type 3d_triggers
$scoreboard players reset 3d_triggers.$(node).triggered 3d_triggers

# Remove all the data
$data remove storage 3d_triggers $(node)

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [3D Triggers]: ","color":"green","bold":false},{"text":"Deleted node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}