# Do not edit this file.


# Pulling the dialogue node data from the first index
data modify storage 3d_triggers node_list.value set from storage 3d_triggers node_list.data[0]

# Setting the dialogue node id
scoreboard players set 3d_triggers.node_list.id dialogues 1
execute store result storage 3d_triggers node_list.active_id int 1 run scoreboard players get 3d_triggers.node_list.id 3d_triggers

# Pulling the dialogue size
execute store result score 3d_triggers.node_list.size 3d_triggers run data get storage 3d_triggers node_list.data

# Dev mode debug
execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [3D Triggers]: ","color":"green","bold":false},{"text":"Deleted all nodes: ","color":"gold","bold":false},{"color":"yellow","bold":false,"score":{"name":"3d_triggers.node_list.size","objective":"3d_triggers"}}]}

scoreboard players add 3d_triggers.node_list.size 3d_triggers 1

# Starting the recursive iterator function
function modules:3d_triggers/private/_delete_all with storage 3d_triggers node_list