# Do not edit this file.


# Safe call
execute unless score KFrame.3d_triggers KFrame matches 1 if score KFrame.dev_mode KFrame matches 1 run return run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [3D Triggers]: ","color":"green","bold":false},{"text":"The module is not on!","color":"red","bold":false}]}
execute unless score 3d_triggers.move 3d_triggers matches 0..1 run scoreboard players set 3d_triggers.move 3d_triggers 0

# Setting up the offset
$data modify storage 3d_triggers node_list.offset set value $(offset)
# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [3D Triggers]: ","color":"green","bold":false},{"text":"Move function called: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}

# Toggling the lock state 0/1 for the specified trigger
$data modify storage 3d_triggers node_list.selected set value $(node)
execute if score 3d_triggers.move 3d_triggers matches 1 run return run scoreboard players set 3d_triggers.move 3d_triggers 0
execute if score 3d_triggers.move 3d_triggers matches 0 run return run scoreboard players set 3d_triggers.move 3d_triggers 1