# Do not edit this file.


# Resetting the trigger value for single uses
$scoreboard players set 3d_triggers.$(node).triggered 3d_triggers 0

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [3D Triggers]: ","color":"green","bold":false},{"text":"Reset node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false}]}