# Do not edit this file.


# Displaying the dialogue
$execute as $(selector) if entity @s[type=text_display] run data modify entity @s text set value [$(author),$(display)]
$execute as $(selector) if entity @s[type=player] run title @s actionbar [$(author),$(display)]

# Incrementation by step | char += step
$scoreboard players operation dialogue.$(id).char dialogues += dialogue.$(id).step dialogues

# Pulling from char scoreboard to storage char
$execute store result storage dialogue $(id).char int 1 run scoreboard players get dialogue.$(id).char dialogues

# Append display.text[0] += text[char]
$data modify storage dialogue $(id).display.text set string storage dialogue $(id).text 0 $(char)

# If char >= len : display.text = text
$execute if score dialogue.$(id).char dialogues > dialogue.$(id).len dialogues run data modify storage dialogue $(id).display.text set string storage dialogue $(id).text 0 $(len)
$execute unless score dialogue.$(id).char dialogues <= dialogue.$(id).len dialogues if score dialogue.$(id).delay dialogues matches $(delay) run function modules:dialogue/private/_stop_run with storage dialogue $(id)

# Executing user input command
$execute unless score dialogue.$(id).char dialogues >= dialogue.$(id).len dialogues run $(command)