# Do not edit this file.


# Clearing the temporary data
scoreboard players reset dialogues.node_list.id dialogues
scoreboard players reset dialogues.node_list.size dialogues
$data remove storage $(storage) node_list