# Do not edit this file.


# Clearing the display after delayed display
$execute as $(selector) if entity @s[type=text_display] run data modify entity @s text set value ""
$execute as $(selector) if entity @s[type=player] run title @s actionbar ""
