# Do not edit this file


# Delayed display
$execute as $(selector) if entity @s[type=text_display] run data modify entity @s text set value [$(author),$(display)]
$execute as $(selector) if entity @s[type=player] run title @s actionbar [$(author),$(display)]

$scoreboard players remove dialogue.$(id).stay dialogues 1