# Do not edit this file.


# Pulling the dialogue data from the storage
$function modules:dialogue/delete {node:$(value)}
$data remove storage dialogue $(value)

# Incrementing the dialogue ID
scoreboard players add dialogues.node_list.id dialogues 1
execute store result storage dialogue node_list.active_id int 1 run scoreboard players get dialogues.node_list.id dialogues

# Pulling the dialogue data from the storage
$data modify storage dialogue node_list.value set from storage dialogue node_list.data[$(active_id)]

# If the dialogue is not iterated through, run the function again
execute unless score dialogues.node_list.id dialogues >= dialogues.node_list.size dialogues run function modules:dialogue/private/_delete_all_nodes with storage dialogue node_list

# If the dialogue is iterated through fully, delete the temporary data
execute if score dialogues.node_list.id dialogues = dialogues.node_list.size dialogues run function modules:dialogue/private/_clear_temp {storage:dialogue}