# Do not edit this file.


# Pulling the dialogue data from the storage
$function modules:dialogue/delete_preset {name:$(value)}

# Incrementing the dialogue ID
scoreboard players add dialogues.node_list.id dialogues 1
execute store result storage dialogue_presets node_list.active_id int 1 run scoreboard players get dialogues.node_list.id dialogues

# Pulling the dialogue data from the storage
$data modify storage dialogue_presets node_list.value set from storage dialogue_presets node_list.data[$(active_id)]

# If the dialogue is not iterated through, run the function again
execute unless score dialogues.node_list.id dialogues >= dialogues.node_list.size dialogues run function modules:dialogue/private/_delete_all_presets with storage dialogue_presets node_list

# If the dialogue is iterated through fully, delete the temporary data
execute if score dialogues.node_list.id dialogues = dialogues.node_list.size dialogues run function modules:dialogue/private/_clear_temp {storage:dialogue_presets}