# Do not edit this file.


$scoreboard players add dialogue.$(id).queue_index dialogues.queue 1
$execute store result storage dialogue_queues $(id).index int 1 run scoreboard players get dialogue.$(id).queue_index dialogues.queue

$function modules:dialogue/private/_change_queue_current with storage dialogue_queues $(id)