# Do not edit this file.


# Iteration with the current node
$function modules:dialogue/iterate {node:$(current)}

# Incrementing the list to change the current node
$execute if score dialogue.$(id).queue_index dialogues.queue < dialogue.$(id).queue_len dialogues.queue if score dialogue.$(current).run dialogues matches 0 if score dialogue.$(current).stay dialogues matches ..1 run function modules:dialogue/private/_increment_queue_index with storage dialogue_queues $(id)