# Do not edit this file.


# Changing index back to 0
$data modify storage dialogue_queues $(id).current set from storage dialogue_queues $(id).list[0]
$data modify storage dialogue_queues $(id).index set value 0
$scoreboard players set dialogue.$(id).queue_index dialogues.queue 0

# Pulling the dialogue node data from the first index
$data modify storage dialogue_queues node_list.value set from storage dialogue_queues $(id).list[0]

$data modify storage dialogue_queues node_list.current_id set from storage dialogue_queues $(id).id

# Setting the dialogue node id
scoreboard players set dialogues.node_list.id dialogues 1
execute store result storage dialogue_queues node_list.active_id int 1 run scoreboard players get dialogues.node_list.id dialogues

# Pulling the dialogue size
$execute store result score dialogues.node_list.size dialogues run data get storage dialogue_queues $(id).list
scoreboard players add dialogues.node_list.size dialogues 1

# Starting the recursive iterator function
function modules:dialogue/private/_reset_queue with storage dialogue_queues node_list

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Dialogue]: ","color":"green","bold":false},{"text":"Reset queue: ","color":"gold","bold":false},{"text":"$(id) ","color":"yellow","bold":false}]}