# Do not edit this file.


# Pulling the dialogue data from the storage
$function modules:dialogue/reset {node:$(value)}

# Pulling the dialogue data from the storage
$data modify storage dialogue_queues node_list.value set from storage dialogue_queues $(current_id).list[$(active_id)]

# Incrementing the dialogue ID
scoreboard players add dialogues.node_list.id dialogues 1
execute store result storage dialogue_queues node_list.active_id int 1 run scoreboard players get dialogues.node_list.id dialogues

# If the dialogue is not iterated through, run the function again
execute unless score dialogues.node_list.id dialogues >= dialogues.node_list.size dialogues run function modules:dialogue/private/_reset_queue with storage dialogue_queues node_list

# If the dialogue is iterated through fully, delete the temporary data
execute if score dialogues.node_list.id dialogues = dialogues.node_list.size dialogues run function modules:dialogue/private/_clear_temp {storage:"dialogue_queues.-"}