# Do not edit this file.


# Stopping the run score
$scoreboard players set dialogue.$(id).run dialogues 0

# Displaying the dialogue
$execute as $(selector) if entity @s[type=text_display] run data modify entity @s text set value [$(author),$(display)]
$execute as $(selector) if entity @s[type=player] run title @s actionbar [$(author),$(display)]