# Do not edit this file.


# Redirection to the main namespace
function main:on_tick

# Module control
execute if score KFrame.inputs KFrame matches 1 run function modules:inputs/private/_tick
execute if score KFrame.3d_triggers KFrame matches 1 run function modules:3d_triggers/private/_tick

# Running internals for the on_start base function
execute as @a run function core:private/_on_start_check