# Do not edit this file.


# Redirection to the main namespace
function main:on_load

# Module control
execute if score KFrame.inputs KFrame matches 1 run function modules:inputs/private/_load

# Creating core scoreboards
scoreboard objectives add KFrame dummy
scoreboard objectives add KFrame.load minecraft.custom:minecraft.leave_game