# Do not edit this file.


# Creating the preset
$data merge storage dialogue_presets {$(name):{author:$(author),step:$(step),selector:"$(selector)",display:$(display),char:$(step),command:"$(command)",delay:$(delay),stay:$(stay)}}