# Do not edit this file.


# Redirecting with the selected preseta
$data modify storage dialogue_presets $(name).text set value "$(text)"
$data modify storage dialogue_presets $(name).node set value "$(node)"

$function dialogue:create with storage dialogue_presets $(name)