# Do not edit this file.


# Deleting all the data connected to the dialogue
$data remove storage dialogue $(node)
$scoreboard players reset .dialogue.$(node).len
$scoreboard players reset .dialogue.$(node).step
$scoreboard players reset .dialogue.$(node).char
$scoreboard players reset .dialogue.$(node).delay