# Do not edit this file.


# Removing all the data
$data remove storage dialogue_queues $(name)
$scoreboard players reset .dialogue.$(name).queue_len dialogues.queue
$scoreboard players reset .dialogue.$(name).queue_index dialogues.queue