# Do not edit this file.


# Changing index back to 0
$data modify storage dialogue_queues $(name).current set from storage dialogue_queues $(name).list[0]
$data modify storage dialogue_queues $(name).index set value 0
$scoreboard players set .dialogue.$(name).queue_index dialogues.queue 0