# Do not edit this file.


# Iteration with the current node
$function dialogue:iterate {node:$(current)}

# Incrementing the list to change the current node
$execute if score .dialogue.$(id).queue_index dialogues.queue < .dialogue.$(id).queue_len dialogues.queue if score .dialogue.$(current).char dialogues >= .dialogue.$(current).len dialogues if score .dialogue.$(current).stay dialogues matches ..1 run function dialogue:private/_increment_queue_index with storage dialogue_queues $(id)