# Do not edit this file.


$scoreboard players set .dialogue.$(id).char dialogues $(step)
$data modify storage minecraft:dialogue $(id).display.text set string storage minecraft:dialogue $(id).text 0 $(step)
$execute as $(selector) if entity @s[type=text_display] run data modify entity @s text set value ""