# Do not edit this file.


# Iterate through the text until it ends
$execute if score .dialogue.$(id).char dialogues <= .dialogue.$(id).len dialogues if score .dialogue.$(id).delay dialogues matches $(delay) run function dialogue:private/activate with storage dialogue $(id)
$execute if score .dialogue.$(id).char dialogues <= .dialogue.$(id).len dialogues if score .dialogue.$(id).delay dialogues matches $(delay).. run scoreboard players set .dialogue.$(id).delay dialogues 0
$execute if score .dialogue.$(id).char dialogues <= .dialogue.$(id).len dialogues if score .dialogue.$(id).delay dialogues matches ..$(delay) run scoreboard players add .dialogue.$(id).delay dialogues 1