# Do not edit this file.


# Displaying the dialogue
$title $(selector) actionbar [$(author),$(display)]

# Incrementation by step | char += step
$scoreboard players operation .kf_dialogue.$(id).char kf_dialogues += .kf_dialogue.$(id).step kf_dialogues

# Pulling from char scoreboard to storage char
$execute store result storage kf_dialogue $(id).char int 1 run scoreboard players get .kf_dialogue.$(id).char kf_dialogues

# Append display.text[0] += text[char]
$data modify storage kf_dialogue $(id).display.text set string storage kf_dialogue $(id).text 0 $(char)

# If char >= len : display.text = text
$execute if score .kf_dialogue.$(id).char kf_dialogues >= .kf_dialogue.$(id).len kf_dialogues run data modify storage kf_dialogue $(id).display.text set string storage kf_dialogue $(id).text 0 $(len)

# Executing user input command
$execute run $(command)
