# Do not edit this file.


# Creating timers main scoreboard
scoreboard objectives add kf_timers dummy

# Creating a timers storage
$data merge storage kf_timers {$(node):{id:$(node),t:0,h:$(h),m:$(m),s:$(s),end_h:$(end_h),end_m:$(end_m),end_s:$(end_s),single:$(single),command:"$(command)"}}

# Saving all the data in the scoreboards
$scoreboard players set .kf_timers.$(node).tick kf_timers 0
$execute store result score .kf_timers.$(node).single kf_timers run data get storage kf_timers $(node).single
$execute store result score .kf_timers.$(node).h kf_timers run data get storage kf_timers $(node).h
$execute store result score .kf_timers.$(node).m kf_timers run data get storage kf_timers $(node).m
$execute store result score .kf_timers.$(node).s kf_timers run data get storage kf_timers $(node).s
$execute store result score .kf_timers.$(node).end_h kf_timers run data get storage kf_timers $(node).end_h
$execute store result score .kf_timers.$(node).end_m kf_timers run data get storage kf_timers $(node).end_m
$execute store result score .kf_timers.$(node).end_s kf_timers run data get storage kf_timers $(node).end_s