# Do not edit this file.


# Deleting data and scoreboard tied to the timer
$data remove storage kf_timers $(node)
$scoreboard players reset .kf_timers.$(node).single kf_timers
$scoreboard players reset .kf_timers.$(node).t kf_timers
$scoreboard players reset .kf_timers.$(node).h kf_timers
$scoreboard players reset .kf_timers.$(node).m kf_timers
$scoreboard players reset .kf_timers.$(node).s kf_timers
$scoreboard players reset .kf_timers.$(node).end_h kf_timers
$scoreboard players reset .kf_timers.$(node).end_m kf_timers
$scoreboard players reset .kf_timers.$(node).end_s kf_timers
$scoreboard players reset .kf_timers.$(node).end_t kf_timers