# Do not edit this file.


# If timers runs to its point - execute the command
$execute if score .kf_timers.$(node).t kf_timers = .kf_timers.$(node).end_t kf_timers if score .kf_timers.$(node).s kf_timers = .kf_timers.$(node).end_s kf_timers if score .kf_timers.$(node).m kf_timers = .kf_timers.$(node).end_m kf_timers if score .kf_timers.$(node).h kf_timers = .kf_timers.$(node).end_h kf_timers run function kf_timers:private/execute with storage kf_timers $(node)

# Iteration process
$execute if score .kf_timers.$(node).t kf_timers matches 0.. if score .kf_timers.$(node).single kf_timers matches 0 unless score .kf_timers.$(node).s kf_timers = .kf_timers.$(node).end_s kf_timers run scoreboard players add .kf_timers.$(node).t kf_timers 1
$execute if score .kf_timers.$(node).t kf_timers matches 0.. if score .kf_timers.$(node).single kf_timers matches 0 unless score .kf_timers.$(node).m kf_timers = .kf_timers.$(node).end_m kf_timers run scoreboard players add .kf_timers.$(node).t kf_timers 1
$execute if score .kf_timers.$(node).t kf_timers matches 0.. if score .kf_timers.$(node).single kf_timers matches 0 unless score .kf_timers.$(node).h kf_timers = .kf_timers.$(node).end_h kf_timers run scoreboard players add .kf_timers.$(node).t kf_timers 1
$execute if score .kf_timers.$(node).t kf_timers matches 0.. if score .kf_timers.$(node).single kf_timers matches 1.. run scoreboard players add .kf_timers.$(node).t kf_timers 1

# Incrementings values
$execute if score .kf_timers.$(node).t kf_timers matches 20.. run function kf_timers:private/increment_s with storage kf_timers $(node)
$execute if score .kf_timers.$(node).s kf_timers matches 60.. run function kf_timers:private/increment_m with storage kf_timers $(node)
$execute if score .kf_timers.$(node).m kf_timers matches 60.. run function kf_timers:private/increment_h with storage kf_timers $(node)

# Storing them back in data
$execute store result storage kf_timers $(node).h int 1 run scoreboard players get .kf_timers.$(node).h kf_timers
$execute store result storage kf_timers $(node).m int 1 run scoreboard players get .kf_timers.$(node).m kf_timers
$execute store result storage kf_timers $(node).s int 1 run scoreboard players get .kf_timers.$(node).s kf_timers
$execute store result storage kf_timers $(node).t int 1 run scoreboard players get .kf_timers.$(node).t kf_timers