# Do not edit this file.


# Getting rid of the same id trigger
$function 3d_triggers:delete with storage 3d_triggers $(node)

# Creating the base scoreboard for 3d triggers
scoreboard objectives add 3d_triggers dummy
scoreboard players set .3d_triggers.debug 3d_triggers 0
scoreboard players set .3d_triggers.move 3d_triggers 0
$scoreboard players set .3d_triggers.$(node).triggered 3d_triggers 0

# Creating the storage
$data merge storage 3d_triggers {$(node):{id:$(node),x:0,y:0,z:0,dx:$(dx),dy:$(dy),dz:$(dz),scaleX:0,scaleY:0,scaleZ:0,command:"$(command)",single:$(single),selector:"$(selector)",color:"$(color)"}}

# Pull players coordinates and store them in xyz of the node storage
execute store result score .tempX 3d_triggers run data get entity @s Pos[0] 100
execute store result score .tempY 3d_triggers run data get entity @s Pos[1] 100
execute store result score .tempZ 3d_triggers run data get entity @s Pos[2] 100

$execute store result storage 3d_triggers $(node).x double 0.01 run scoreboard players get .tempX 3d_triggers
$execute store result storage 3d_triggers $(node).y double 0.01 run scoreboard players get .tempY 3d_triggers
$execute store result storage 3d_triggers $(node).z double 0.01 run scoreboard players get .tempZ 3d_triggers

# Getting the "single" arg
$execute store result score .3d_triggers.$(node).single 3d_triggers run data get storage 3d_triggers $(node).single

# Pulling dx dy dz from storage to check if it's less than zero, in case of - set it to 0
$execute store result score .3d_triggers.$(node).x 3d_triggers run data get storage 3d_triggers $(node).dx 1
$execute store result score .3d_triggers.$(node).y 3d_triggers run data get storage 3d_triggers $(node).dy 1
$execute store result score .3d_triggers.$(node).z 3d_triggers run data get storage 3d_triggers $(node).dz 1

$execute if score .3d_triggers.$(node).x 3d_triggers matches ..0 run data modify storage 3d_triggers $(node).dx set value 0
$execute if score .3d_triggers.$(node).y 3d_triggers matches ..0 run data modify storage 3d_triggers $(node).dy set value 0
$execute if score .3d_triggers.$(node).z 3d_triggers matches ..0 run data modify storage 3d_triggers $(node).dz set value 0

# With xyz scoreboard, getting the value from dx dy dz and incrementing it to create a block_display to represent it's size
$execute store result score .3d_triggers.$(node).x 3d_triggers run data get storage 3d_triggers $(node).dx 1
$execute store result score .3d_triggers.$(node).y 3d_triggers run data get storage 3d_triggers $(node).dy 1
$execute store result score .3d_triggers.$(node).z 3d_triggers run data get storage 3d_triggers $(node).dz 1

$scoreboard players add .3d_triggers.$(node).x 3d_triggers 1
$scoreboard players add .3d_triggers.$(node).y 3d_triggers 1
$scoreboard players add .3d_triggers.$(node).z 3d_triggers 1

$execute store result storage 3d_triggers $(node).scaleX int 1 run scoreboard players get .3d_triggers.$(node).x 3d_triggers
$execute store result storage 3d_triggers $(node).scaleY int 1 run scoreboard players get .3d_triggers.$(node).y 3d_triggers
$execute store result storage 3d_triggers $(node).scaleZ int 1 run scoreboard players get .3d_triggers.$(node).z 3d_triggers

# Resetting scoreboards
$scoreboard players reset .3d_triggers.$(node).x
$scoreboard players reset .3d_triggers.$(node).y
$scoreboard players reset .3d_triggers.$(node).z

scoreboard players reset .tempX 3d_triggers
scoreboard players reset .tempY 3d_triggers
scoreboard players reset .tempZ 3d_triggers

