# Do not edit this file.


# Kill all entities connected to the trigger
$kill @e[tag=kf.$(node).trigger]
$data remove storage 3d_triggers $(node)

$scoreboard players reset .3d_triggers.$(node).single 3d_triggers
$scoreboard players reset .3d_triggers.$(node).triggered 3d_triggers