# Do not edit this file.


# Toggle the debug
execute if score .3d_triggers.move 3d_triggers matches 0 run return run scoreboard players set .3d_triggers.move 3d_triggers 1
execute if score .3d_triggers.move 3d_triggers matches 1 run return run scoreboard players set .3d_triggers.move 3d_triggers 0