# Do not edit this file.


$data modify storage kf_timers $(id).h set value $(value)
$data modify storage kf_timers $(id).init.[].h set value $(value)
$execute store result score .kf_timers.$(id).h kf_timers run data get storage kf_timers $(id).h 1