# Do not edit this file.


$data modify storage kf_timers $(id).end_m set value $(value)
$data modify storage kf_timers $(id).init.[].end_m set value $(value)
$execute store result score .kf_timers.$(id).end_m kf_timers run data get storage kf_timers $(id).end_m 1