# Do not edit this file.


$data modify storage kf_timers $(id).t set value $(value)
$data modify storage kf_timers $(id).init.[].t set value $(value)
$execute store result score .kf_timers.$(id).t kf_timers run data get storage kf_timers $(id).t 1