# Do not edit this file.


$data modify storage kf_timers $(id).end_h set value $(value)
$data modify storage kf_timers $(id).init.[].end_h set value $(value)
$execute store result score .kf_timers.$(id).end_h kf_timers run data get storage kf_timers $(id).end_h 1