# Do not edit this file.


$data modify storage kf_timers $(id).m set value $(value)
$data modify storage kf_timers $(id).init.[].m set value $(value)
$execute store result score .kf_timers.$(id).m kf_timers run data get storage kf_timers $(id).m 1