# Do not edit this file.


$data modify storage kf_timers $(id).end_s set value $(value)
$data modify storage kf_timers $(id).init.[].end_s set value $(value)
$execute store result score .kf_timers.$(id).end_s kf_timers run data get storage kf_timers $(id).end_s 1