# Do not edit this file.


$data modify storage kf_timers $(id).end_t set value $(value)
$data modify storage kf_timers $(id).init.[].end_t set value $(value)
$execute store result score .kf_timers.$(id).end_t kf_timers run data get storage kf_timers $(id).end_t 1