# Do not edit this file


# Debug display
$execute if score .3d_triggers.debug 3d_triggers matches 1 positioned $(x) $(y) $(z) if entity @a[dx=$(dx),dy=$(dy),dz=$(dz)] run title @a actionbar {"color":"green","text":"TRIGGERED!"}
$execute if score .3d_triggers.debug 3d_triggers matches 1 positioned $(x) $(y) $(z) unless entity @a[dx=$(dx),dy=$(dy),dz=$(dz)] run title @a actionbar {"color":"red","text":"TRIGGERED!"}

# Display triggers anchor
$execute if score .3d_triggers.debug 3d_triggers matches 1 positioned $(x) $(y) $(z) run particle bubble ~ ~ ~ 0.01 0.01 0.01 0 1 force @a

# Display stained glass if debug is on
$execute if score .3d_triggers.debug 3d_triggers matches 1 unless entity @e[tag=kf.$(id).trigger] run function 3d_triggers:private/_summon_display with storage 3d_triggers $(id)
execute if score .3d_triggers.debug 3d_triggers matches 0 run kill @e[tag=kf.trigger]

# Display the name
$data merge entity @n[type=block_display,tag=kf.$(id).trigger] {CustomNameVisible:1b,CustomName:"Trigger: [$(id)]",block_state:{Name:"minecraft:$(color)_stained_glass"}}

# Check if entity is inside of the dx dy dz
$execute if score .3d_triggers.$(id).single 3d_triggers matches 0 positioned $(x) $(y) $(z) as $(selector) if entity @s[dx=$(dx),dy=$(dy),dz=$(dz)] run $(command)

# Check if entity is inside of the dx dy dz + single use
$execute if score .3d_triggers.$(id).single 3d_triggers matches 1 if score .3d_triggers.$(id).triggered 3d_triggers matches 0 positioned 0 0 0 positioned $(x) $(y) $(z) as $(selector) if entity @s[dx=$(dx),dy=$(dy),dz=$(dz)] run function 3d_triggers:private/_redirect with storage 3d_triggers $(id)

# Tp block_display to the anchor
$execute positioned $(x) $(y) $(z) run tp @n[tag=kf.$(id).trigger] ~ ~ ~

# Getting precise coordinates
execute if score .3d_triggers.move 3d_triggers matches 1 store result score .tempX 3d_triggers run data get entity @n[type=player] Pos[0] 100
execute if score .3d_triggers.move 3d_triggers matches 1 store result score .tempY 3d_triggers run data get entity @n[type=player] Pos[1] 100
execute if score .3d_triggers.move 3d_triggers matches 1 store result score .tempZ 3d_triggers run data get entity @n[type=player] Pos[2] 100

# Converting coordinates back to double
$execute if score .3d_triggers.move 3d_triggers matches 1 store result storage 3d_triggers $(id).x double 0.01 run scoreboard players get .tempX 3d_triggers
$execute if score .3d_triggers.move 3d_triggers matches 1 store result storage 3d_triggers $(id).y double 0.01 run scoreboard players get .tempY 3d_triggers
$execute if score .3d_triggers.move 3d_triggers matches 1 store result storage 3d_triggers $(id).z double 0.01 run scoreboard players get .tempZ 3d_triggers

# Setting temp to null
scoreboard players reset .tempX 3d_triggers
scoreboard players reset .tempY 3d_triggers
scoreboard players reset .tempZ 3d_triggers