# Do not edit this file.


# Create score base
scoreboard objectives add kf_dialogues dummy
scoreboard players set #kf_dialogues_const1 kf_dialogues 1

# Creating a dialogue storage
$data merge storage kf_dialogue {$(node):{text:"$(text)",author:$(author),step:$(step),selector:"$(selector)",display:$(display),id:"$(node)",len:0,char:$(step),command:"$(command)",delay:$(delay)}}

# Getting the text's length and storing it
$execute store result score .kf_dialogue.$(node).len kf_dialogues run data get storage kf_dialogue $(node).text
$execute store result storage kf_dialogue $(node).len int 1 run scoreboard players get .kf_dialogue.$(node).len kf_dialogues

# Setting up the display.text with the first (or a couple of, depending on step) symbols
$data modify storage minecraft:kf_dialogue $(node).display.text set string storage minecraft:kf_dialogue $(node).text 0 $(step)

# Setting up delay timer
$scoreboard players set .kf_dialogue.$(node).delay kf_dialogues 0

# Setting up char counter
$scoreboard players set .kf_dialogue.$(node).char kf_dialogues $(step)

# Checking if text length is bigger than step value. If not - change step to 1
$scoreboard players set .kf_dialogue.$(node).step kf_dialogues $(step)
$execute if score .kf_dialogue.$(node).step kf_dialogues > .kf_dialogue.$(node).len kf_dialogues run data modify storage kf_dialogue $(node).step set value 1
$execute if score .kf_dialogue.$(node).step kf_dialogues > .kf_dialogue.$(node).len kf_dialogues run data modify storage kf_dialogue $(node).display.text set string storage minecraft:kf_dialogue $(node).text 0 1
$execute store result score .kf_dialogue.$(node).step kf_dialogues run data get storage kf_dialogue $(node).step 1