# Do not edit this file.


# Deleting all the data connected to the dialogue
$data remove storage kf_dialogue $(node)
$scoreboard players reset .kf_dialogue.$(node).len
$scoreboard players reset .kf_dialogue.$(node).step
$scoreboard players reset .kf_dialogue.$(node).char
$scoreboard players reset .kf_dialogue.$(node).delay