# Do not edit this file.


$scoreboard players set .kf_dialogue.$(id).char kf_dialogues $(step)
$data modify storage minecraft:kf_dialogue $(id).display.text set string storage minecraft:kf_dialogue $(id).text 0 $(step)