# Do not edit this file.


# Store the entity count in the temporary score and print it
$execute store result score #KF_TEMP KFrame if entity @e[type=minecraft:$(type)]
$tellraw @a [{"color":"green","text":"$(type): "},{"color":"yellow","score":{"name":"#KF_TEMP","objective":"KFrame"}}]