# Do not edit this file.


# If ANY input is triggered, and the input is unlocked - return 1
execute if entity @s[predicate=modules:inputs/w_input,scores={inputs.w_lock=0}] run return 1
execute if entity @s[predicate=modules:inputs/a_input,scores={inputs.a_lock=0}] run return 1
execute if entity @s[predicate=modules:inputs/s_input,scores={inputs.s_lock=0}] run return 1
execute if entity @s[predicate=modules:inputs/d_input,scores={inputs.d_lock=0}] run return 1
execute if entity @s[predicate=modules:inputs/sprint_input,scores={inputs.ctrl_lock=0}] run return 1
execute if entity @s[predicate=modules:inputs/shift_input,scores={inputs.shift_lock=0}] run return 1
execute if entity @s[predicate=modules:inputs/space_input,scores={inputs.space_lock=0}] run return 1