# Do not edit this file.


# Getting the data that will be appended to the quicksave node
$data modify storage minecraft:quicksaves $(node).input.score set value "$(score)"
$data modify storage minecraft:quicksaves $(node).input.obj set value "$(obj)"
$execute store result storage minecraft:quicksaves $(node).input.value int 1 run scoreboard players get $(score) $(obj)

# Copying id to the temp.id
$data modify storage quicksaves $(node).input.id set from storage quicksaves $(node).id

# Setting up a temporary scoreboard to track the size of the quicksave node
$data modify storage minecraft:quicksaves $(node).input.temp set value 0
$scoreboard players set quicksave.$(node).temp quicksave 0

# Pulling the size of the quicksave node
$execute store result score quicksave.$(node).size quicksave run data get storage minecraft:quicksaves $(node).data

# Checking for the empty quicksave slots
$function modules:quicksave/private/_check_data with storage quicksaves $(node).input

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Quicksave]: ","color":"green","bold":false},{"text":"Append to node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false},{"text":"with: ","color":"gold","bold":false},{"text":"score: ","color":"gold","bold":false},{"text":"$(score) ","color":"light_purple","bold":false},{"text":"obj: ","color":"gold","bold":false},{"text":"$(obj) ","color":"light_purple","bold":false},{"text":"value: ","color":"gold","bold":false},{"color":"light_purple","bold":false,"score":{"name":"$(score)","objective":"$(obj)"}}]}