# Do not edit this file.


# Pulling the quicksave node data from the first index
$data modify storage quicksaves $(node).input.active_node set value $(node)
$data modify storage quicksaves $(node).input.score set from storage quicksaves $(node).data[0].score
$data modify storage quicksaves $(node).input.value set from storage quicksaves $(node).data[0].value
$data modify storage quicksaves $(node).input.obj set from storage quicksaves $(node).data[0].obj

# Setting the quicksave node id
$scoreboard players set quicksave.$(node).id quicksave 0
$execute store result storage quicksaves $(node).input.active_id int 1 run scoreboard players get quicksave.$(node).id quicksave

# Pulling the quicksave size
$execute store result score quicksave.$(node).size quicksave run data get storage minecraft:quicksaves $(node).data
$scoreboard players add quicksave.$(node).size quicksave 1

# Starting the recursive iterator function
$function modules:quicksave/private/_clear_iterator with storage quicksaves $(node).input

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Quicksave]: ","color":"green","bold":false},{"text":"Cleared node: ","color":"gold","bold":false},{"text":"$(node)","color":"yellow","bold":false}]}