# Do not edit this file.


# Clearing the leftover data
$function modules:quicksave/private/_delete with storage quicksaves $(node)

# Creating a new quicksave node
$data merge storage quicksaves {$(node):{id:$(node),size:$(size),"data":[]}}
$data modify storage quicksaves node_list.data append value $(node)

# Setting the size of the quicksave node
scoreboard objectives add quicksave dummy
$scoreboard players set quicksave.$(node).size quicksave $(size)
$scoreboard players set quicksave.$(node).temp quicksave 0

# If the node size is less than 1 - delete the node
$execute if score quicksave.$(node).size quicksave matches ..0 run function modules:quicksave/private/_delete with storage quicksaves $(node)

# Append the size of the quicksave node
$function modules:quicksave/private/_add_size with storage quicksaves $(node)

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Quicksave]: ","color":"green","bold":false},{"text":"Node created: ","color":"gold","bold":false},{"text":"$(node)","color":"yellow","bold":false}]}