# Do not edit this file.


# Pulling the quicksave node data from the first index
data modify storage quicksaves node_list.value set from storage quicksaves node_list.data[0]

# Setting the quicksave node id
scoreboard players set quicksave.node_list.id quicksave 0
execute store result storage quicksaves node_list.active_id int 1 run scoreboard players get quicksave.node_list.id quicksave

# Pulling the quicksave size
execute store result score quicksave.node_list.size quicksave run data get storage minecraft:quicksaves node_list.data
scoreboard players add quicksave.node_list.size quicksave 1

# Starting the recursive iterator function
function modules:quicksave/private/_delete_all with storage quicksaves node_list

# Dev mode debug
execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Quicksave]: ","color":"green","bold":false},{"text":"Deleted all nodes","color":"gold","bold":false}]}