# Do not edit this file.


# Removing a quicksave node
$function modules:quicksave/private/_delete with storage quicksaves $(node)

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Quicksave]: ","color":"green","bold":false},{"text":"Node deleted: ","color":"gold","bold":false},{"text":"$(node)","color":"yellow","bold":false}]}