# Do not edit this file.


# Expanding the quicksave node size
$scoreboard players set quicksave.$(node).size quicksave $(size)
$scoreboard players set quicksave.$(node).temp quicksave 0

# Running the _add_size function to add the size to the quicksave node
$execute if score quicksave.$(node).size quicksave matches 1.. run function modules:quicksave/private/_add_size with storage quicksaves $(node)

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Quicksave]: ","color":"green","bold":false},{"text":"Grew node ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false},{"text":"by ","color":"gold","bold":false},{"text":"$(size) ","color":"yellow","bold":false}]}