# Do not edit this file.


# Clearting the quicksave node slot
$data modify storage quicksaves $(node).data[$(id)].score set value ""
$data modify storage quicksaves $(node).data[$(id)].obj set value ""
$data modify storage quicksaves $(node).data[$(id)].value set value 0

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Quicksave]: ","color":"green","bold":false},{"text":"Popped node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false},{"text":"by ID: ","color":"gold","bold":false},{"text":"$(id)","color":"yellow","bold":false}]}