# Do not edit this file.


# Pulling the quicksave node data
$data modify storage quicksaves $(node).input.active_node set value $(node)
$data modify storage quicksaves $(node).input.score set from storage quicksaves $(node).data[0].score
$data modify storage quicksaves $(node).input.value set from storage quicksaves $(node).data[0].value
$data modify storage quicksaves $(node).input.obj set from storage quicksaves $(node).data[0].obj

# Displaying the quicksave node id
$tellraw @a [{"text":"\nQuicksave Node: "},{"color":"yellow","text":"$(node)\n"}]

$scoreboard players set quicksave.$(node).print.id quicksave 0
$execute store result storage quicksaves $(node).input.print_id int 1 run scoreboard players get quicksave.$(node).print.id quicksave

$scoreboard players set quicksave.$(node).id quicksave 1
$execute store result storage quicksaves $(node).input.active_id int 1 run scoreboard players get quicksave.$(node).id quicksave

$execute store result score quicksave.$(node).size quicksave run data get storage minecraft:quicksaves $(node).data
$scoreboard players add quicksave.$(node).size quicksave 1

$function modules:quicksave/private/_print with storage quicksaves $(node).input