# Do not edit this file.


# Set a quicksave slot with the given ID, score, and objective
$data modify storage quicksaves $(node).data[$(id)].score set value "$(score)"
$data modify storage quicksaves $(node).data[$(id)].obj set value "$(obj)"
$execute store result storage quicksaves $(node).data[$(id)].value int 1 run scoreboard players get $(score) $(obj)

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Quicksave]: ","color":"green","bold":false},{"text":"Set node: ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false},{"text":"by ID: ","color":"gold","bold":false},{"text":"$(id) ","color":"yellow","bold":false},{"text":"with: ","color":"gold","bold":false},{"text":"score: ","color":"gold","bold":false},{"text":"$(score) ","color":"light_purple","bold":false},{"text":"obj: ","color":"gold","bold":false},{"text":"$(obj) ","color":"light_purple","bold":false},{"text":"value: ","color":"gold","bold":false},{"color":"light_purple","bold":false,"score":{"name":"$(score)","objective":"$(obj)"}}]}