# Do not edit this file.


# Shrinking the quicksave node size
$data remove storage quicksaves $(node).data[$(id)]

# Dev mode debug
$execute if score KFrame.dev_mode KFrame matches 1 run tellraw @a {"text":"[K-Frame]","color":"aqua","bold":true,"extra":[{"text":" [Quicksave]: ","color":"green","bold":false},{"text":"Shrunk node ","color":"gold","bold":false},{"text":"$(node) ","color":"yellow","bold":false},{"text":"by ID ","color":"gold","bold":false},{"text":"$(id) ","color":"yellow","bold":false}]}