# Do not edit this file.


# Creating a block display for the trigger
$kill @e[tag=3d_triggers.$(id).display]
$execute unless entity @e[tag=3d_triggers.$(id).display] run summon block_display $(x) $(y) $(z) {Tags:["3d_triggers.$(id).display"],CustomNameVisible:1b,CustomName:"[$(id)]",transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[$(dx)f,$(dy)f,$(dz)f]},block_state:{Name:"minecraft:$(color)_stained_glass"},brightness:{sky:15,block:15}}
$ride @n[tag=3d_triggers.$(id).display] mount @n[tag=3d_triggers.$(id)]