# Do not edit this file.


# Dev mode debug
execute if score KFrame.dev_mode KFrame matches 1 run title @a actionbar {"color":"red","text":"TRIGGERED!"}
$execute if score KFrame.dev_mode KFrame matches 1 if score 3d_triggers.$(id).type 3d_triggers matches 0 at @n[tag=3d_triggers.$(id),type=item_display] as $(selector) if entity @s[dx=0,dy=0,dz=0] positioned ~-$(offset_x) ~-$(offset_y) ~-$(offset_z) if entity @s[dx=0,dy=0,dz=0] positioned ~$(offset_x) ~$(offset_y) ~$(offset_z) run title @a actionbar {"color":"green","text":"TRIGGERED!"}
$execute if score KFrame.dev_mode KFrame matches 1 if score 3d_triggers.$(id).type 3d_triggers matches 1 at @n[tag=3d_triggers.$(id),type=item_display] as $(selector) if entity @s[dx=$(dx),dy=$(dy),dz=$(dz)] run title @a actionbar {"color":"green","text":"TRIGGERED!"}

# If the trigger type is small
$execute if score 3d_triggers.$(id).single 3d_triggers matches 0 if score 3d_triggers.$(id).type 3d_triggers matches 0 at @n[tag=3d_triggers.$(id),type=item_display] as $(selector) if entity @s[dx=0,dy=0,dz=0] positioned ~-$(offset_x) ~-$(offset_y) ~-$(offset_z) if entity @s[dx=0,dy=0,dz=0] positioned ~$(offset_x) ~$(offset_y) ~$(offset_z) run $(command)
$execute if score 3d_triggers.$(id).single 3d_triggers matches 1 if score 3d_triggers.$(id).triggered 3d_triggers matches 0 if score 3d_triggers.$(id).type 3d_triggers matches 0 at @n[tag=3d_triggers.$(id),type=item_display] as $(selector) if entity @s[dx=0,dy=0,dz=0] positioned ~-$(offset_x) ~-$(offset_y) ~-$(offset_z) if entity @s[dx=0,dy=0,dz=0] positioned ~$(offset_x) ~$(offset_y) ~$(offset_z) run function modules:3d_triggers/private/_redirect with storage 3d_triggers $(id)

# If the trigger type is big
$execute if score 3d_triggers.$(id).single 3d_triggers matches 0 if score 3d_triggers.$(id).type 3d_triggers matches 1 at @n[tag=3d_triggers.$(id),type=item_display] as $(selector) if entity @s[dx=$(dx),dy=$(dy),dz=$(dz)] run $(command)
$execute if score 3d_triggers.$(id).single 3d_triggers matches 1 if score 3d_triggers.$(id).triggered 3d_triggers matches 0 if score 3d_triggers.$(id).type 3d_triggers matches 1 at @n[tag=3d_triggers.$(id),type=item_display] as $(selector) if entity @s[dx=$(dx),dy=$(dy),dz=$(dz)] run function modules:3d_triggers/private/_redirect with storage 3d_triggers $(id)