# Do not edit this file.


# Remove data from the storage
data remove storage 3d_triggers node_list

# Resetting the temporary scores
scoreboard players reset 3d_triggers.node_list.id 3d_triggers
scoreboard players reset 3d_triggers.node_list.size 3d_triggers
scoreboard players reset 3d_triggers.move