# Do not edit this file.


# Calculating the offset values
$scoreboard players set 3d_triggers.$(id).temp100 3d_triggers 100
# X
$scoreboard players operation 3d_triggers.$(id).offset_x 3d_triggers = 3d_triggers.$(id).temp100 3d_triggers
$scoreboard players operation 3d_triggers.$(id).offset_x 3d_triggers -= 3d_triggers.$(id).temp1 3d_triggers
# Y
$scoreboard players operation 3d_triggers.$(id).offset_y 3d_triggers = 3d_triggers.$(id).temp100 3d_triggers
$scoreboard players operation 3d_triggers.$(id).offset_y 3d_triggers -= 3d_triggers.$(id).temp2 3d_triggers
# Z
$scoreboard players operation 3d_triggers.$(id).offset_z 3d_triggers = 3d_triggers.$(id).temp100 3d_triggers
$scoreboard players operation 3d_triggers.$(id).offset_z 3d_triggers -= 3d_triggers.$(id).temp3 3d_triggers
# Storing the offset values in storage
$execute store result storage 3d_triggers $(id).offset_x double 0.01 run scoreboard players get 3d_triggers.$(id).offset_x 3d_triggers
$execute store result storage 3d_triggers $(id).offset_y double 0.01 run scoreboard players get 3d_triggers.$(id).offset_y 3d_triggers
$execute store result storage 3d_triggers $(id).offset_z double 0.01 run scoreboard players get 3d_triggers.$(id).offset_z 3d_triggers

# Summoning the item_display that will serve as the anchor
$summon item_display $(x) $(y) $(z) {Tags:["3d_triggers.$(id)"]}

# Creating a type scoreboard for the trigger
$scoreboard players set 3d_triggers.$(id).type 3d_triggers 0

# Resetting all the unnecessary scores
$scoreboard players reset 3d_triggers.$(id).temp1 3d_triggers
$scoreboard players reset 3d_triggers.$(id).temp2 3d_triggers
$scoreboard players reset 3d_triggers.$(id).temp3 3d_triggers
$scoreboard players reset 3d_triggers.$(id).temp100 3d_triggers

$scoreboard players reset 3d_triggers.$(id).offset_x 3d_triggers
$scoreboard players reset 3d_triggers.$(id).offset_y 3d_triggers
$scoreboard players reset 3d_triggers.$(id).offset_z 3d_triggers