# Do not edit this file.


# Getting the "single" arg
$execute store result score 3d_triggers.$(id).single 3d_triggers run data get storage 3d_triggers $(id).single

# Pulling dx dy dz from storage to check if it's less than zero, in case of - set it to 1
$execute store result score 3d_triggers.$(id).temp1 3d_triggers run data get storage 3d_triggers $(id).dx 1
$execute store result score 3d_triggers.$(id).temp2 3d_triggers run data get storage 3d_triggers $(id).dy 1
$execute store result score 3d_triggers.$(id).temp3 3d_triggers run data get storage 3d_triggers $(id).dz 1

# Summoning the item_display that will serve as the anchor
$summon item_display $(x) $(y) $(z) {Tags:["3d_triggers.$(id)"]}

# Creating a type scoreboard for the trigger
$scoreboard players set 3d_triggers.$(id).type 3d_triggers 1

# With xyz scoreboard, getting the value from dx dy dz and incrementing it to create a block_display to represent it's size
$scoreboard players add 3d_triggers.$(id).temp1 3d_triggers 1
$scoreboard players add 3d_triggers.$(id).temp2 3d_triggers 1
$scoreboard players add 3d_triggers.$(id).temp3 3d_triggers 1

$execute store result storage 3d_triggers $(id).scaleX int 1 run scoreboard players get 3d_triggers.$(id).temp1 3d_triggers
$execute store result storage 3d_triggers $(id).scaleY int 1 run scoreboard players get 3d_triggers.$(id).temp2 3d_triggers
$execute store result storage 3d_triggers $(id).scaleZ int 1 run scoreboard players get 3d_triggers.$(id).temp3 3d_triggers

$scoreboard players reset 3d_triggers.$(id).temp1
$scoreboard players reset 3d_triggers.$(id).temp2
$scoreboard players reset 3d_triggers.$(id).temp3