# Do not edit this file.


# If trigger type is 0, run the function to show small trigger block displays
$function modules:3d_triggers/delete {node:$(value)}

# Incrementing the dialogue ID
scoreboard players add 3d_triggers.node_list.id 3d_triggers 1
execute store result storage 3d_triggers node_list.active_id int 1 run scoreboard players get 3d_triggers.node_list.id 3d_triggers

# Pulling the dialogue data from the storage
$data modify storage 3d_triggers node_list.value set from storage 3d_triggers node_list.data[$(active_id)]

# If the dialogue is not iterated through, run the function again
execute unless score 3d_triggers.node_list.id 3d_triggers >= 3d_triggers.node_list.size 3d_triggers run function modules:3d_triggers/private/_delete_all with storage 3d_triggers node_list

# If the dialogue is iterated through fully, delete the temporary data
execute if score 3d_triggers.node_list.id 3d_triggers = 3d_triggers.node_list.size 3d_triggers run function modules:3d_triggers/private/_clear_all_temp