# Do not edit this file.


# Move the trigger node to the new position
$execute if score 3d_triggers.move 3d_triggers matches 1 at @p run tp @n[tag=3d_triggers.$(selected),type=item_display] ^ ^ ^$(offset)