# Do not edit this file.


# If trigger type is 0, run the function to show small trigger block displays
$execute if score 3d_triggers.$(value).type 3d_triggers matches 0 run function modules:3d_triggers/private/_block_display_small with storage 3d_triggers $(value)

# If trigger type is 1, run the function to show big trigger block displays
$execute if score 3d_triggers.$(value).type 3d_triggers matches 1 run function modules:3d_triggers/private/_block_display_big with storage 3d_triggers $(value)

# Incrementing the dialogue ID
scoreboard players add 3d_triggers.node_list.id 3d_triggers 1
execute store result storage 3d_triggers node_list.active_id int 1 run scoreboard players get 3d_triggers.node_list.id 3d_triggers

# Pulling the dialogue data from the storage
$data modify storage 3d_triggers node_list.value set from storage 3d_triggers node_list.data[$(active_id)]

# If the dialogue is not iterated through, run the function again
execute unless score 3d_triggers.node_list.id 3d_triggers >= 3d_triggers.node_list.size 3d_triggers run function modules:3d_triggers/private/_show_block_displays with storage 3d_triggers node_list

# If the dialogue is iterated through fully, delete the temporary data
execute if score 3d_triggers.node_list.id 3d_triggers = 3d_triggers.node_list.size 3d_triggers run function modules:3d_triggers/private/_clear_temp