# Do not edit this file.


# Redirection to the main namespace
function main:on_start

# Locking up the on_start function
# Without the lock on_start function would trigger every single time a new player would enter the world
scoreboard players set #KF_ON_START_LOCK KFrame 1