# Do not edit this file.


$data modify storage quicksaves input.active_node set value $(node)
$data modify storage quicksaves input.score set from storage quicksaves $(node).data[0].score
$data modify storage quicksaves input.value set from storage quicksaves $(node).data[0].value
$data modify storage quicksaves input.obj set from storage quicksaves $(node).data[0].obj

scoreboard players set #quicksave_id quicksave 1
execute store result storage quicksaves input.active_id int 1 run scoreboard players get #quicksave_id quicksave
function quicksave:private/_iterator with storage quicksaves input