# Do not edit this file.


$execute store result storage quicksaves input.id int 1 run data get storage quicksaves $(node).id
$execute store result storage quicksaves input.value int 1 run scoreboard players get $(score) $(obj)

$data modify storage quicksaves input.node set value "$(node)"
$data modify storage quicksaves input.score set value "$(score)"
$data modify storage quicksaves input.obj set value "$(obj)"

function quicksave:private/_import with storage quicksaves input