# Do not edit this file.


$data merge storage quicksaves {$(node):{"id":0,"data":[{"score":"","obj":"","value":0},{"score":"","obj":"","value":0},{"score":"","obj":"","value":0},{"score":"","obj":"","value":0},{"score":"","obj":"","value":0},{"score":"","obj":"","value":0},{"score":"","obj":"","value":0},{"score":"","obj":"","value":0},{"score":"","obj":"","value":0},{"score":"","obj":"","value":0}]}}

scoreboard objectives add quicksave dummy