# Do not edit this file.


$data modify storage quicksaves $(node).data[$(id)].score set value "$(score)"
$data modify storage quicksaves $(node).data[$(id)].obj set value "$(obj)"
$execute store result storage quicksaves $(node).data[$(id)].value int 1 run scoreboard players get $(score) $(obj)