# Do not edit this file.


# Getting rid of the same id trigger
$function kf_3d_triggers:delete with storage kf_3d_triggers $(node)

# Creating the base scoreboard for 3d triggers
scoreboard objectives add kf_3d_triggers dummy
scoreboard players set .kf_3d_triggers.debug kf_3d_triggers 0
scoreboard players set .kf_3d_triggers.move kf_3d_triggers 0
$scoreboard players set .kf_3d_triggers.$(node).triggered kf_3d_triggers 0

# Creating the storage
$data merge storage kf_3d_triggers {$(node):{id:$(node),x:0,y:0,z:0,dx:$(dx),dy:$(dy),dz:$(dz),scaleX:0,scaleY:0,scaleZ:0,command:"$(command)",single:$(single),selector:"$(selector)",color:"red"}}

# Pull players coordinates and store them in xyz of the node storage
execute store result score .kf_tempX kf_3d_triggers run data get entity @s Pos[0] 100
execute store result score .kf_tempY kf_3d_triggers run data get entity @s Pos[1] 100
execute store result score .kf_tempZ kf_3d_triggers run data get entity @s Pos[2] 100

$execute store result storage kf_3d_triggers $(node).x double 0.01 run scoreboard players get .kf_tempX kf_3d_triggers
$execute store result storage kf_3d_triggers $(node).y double 0.01 run scoreboard players get .kf_tempY kf_3d_triggers
$execute store result storage kf_3d_triggers $(node).z double 0.01 run scoreboard players get .kf_tempZ kf_3d_triggers

# Getting the "single" arg
$execute store result score .kf_3d_triggers.$(node).single kf_3d_triggers run data get storage kf_3d_triggers $(node).single

# Pulling dx dy dz from storage to check if it's less than zero, in case of - set it to 0
$execute store result score .kf_3d_triggers.$(node).x kf_3d_triggers run data get storage kf_3d_triggers $(node).dx 1
$execute store result score .kf_3d_triggers.$(node).y kf_3d_triggers run data get storage kf_3d_triggers $(node).dy 1
$execute store result score .kf_3d_triggers.$(node).z kf_3d_triggers run data get storage kf_3d_triggers $(node).dz 1

$execute if score .kf_3d_triggers.$(node).x kf_3d_triggers matches ..0 run data modify storage kf_3d_triggers $(node).dx set value 0
$execute if score .kf_3d_triggers.$(node).y kf_3d_triggers matches ..0 run data modify storage kf_3d_triggers $(node).dy set value 0
$execute if score .kf_3d_triggers.$(node).z kf_3d_triggers matches ..0 run data modify storage kf_3d_triggers $(node).dz set value 0

# With xyz scoreboard, getting the value from dx dy dz and incrementing it to create a block_display to represent it's size
$execute store result score .kf_3d_triggers.$(node).x kf_3d_triggers run data get storage kf_3d_triggers $(node).dx 1
$execute store result score .kf_3d_triggers.$(node).y kf_3d_triggers run data get storage kf_3d_triggers $(node).dy 1
$execute store result score .kf_3d_triggers.$(node).z kf_3d_triggers run data get storage kf_3d_triggers $(node).dz 1

$scoreboard players add .kf_3d_triggers.$(node).x kf_3d_triggers 1
$scoreboard players add .kf_3d_triggers.$(node).y kf_3d_triggers 1
$scoreboard players add .kf_3d_triggers.$(node).z kf_3d_triggers 1

$execute store result storage kf_3d_triggers $(node).scaleX int 1 run scoreboard players get .kf_3d_triggers.$(node).x kf_3d_triggers
$execute store result storage kf_3d_triggers $(node).scaleY int 1 run scoreboard players get .kf_3d_triggers.$(node).y kf_3d_triggers
$execute store result storage kf_3d_triggers $(node).scaleZ int 1 run scoreboard players get .kf_3d_triggers.$(node).z kf_3d_triggers

# Resetting scoreboards
$scoreboard players reset .kf_3d_triggers.$(node).x
$scoreboard players reset .kf_3d_triggers.$(node).y
$scoreboard players reset .kf_3d_triggers.$(node).z

scoreboard players reset .kf_tempX kf_3d_triggers
scoreboard players reset .kf_tempY kf_3d_triggers
scoreboard players reset .kf_tempZ kf_3d_triggers

$function kf_3d_triggers:private/summon_display with storage kf_3d_triggers $(node)

