# Do not edit this file.


# Kill all entities connected to the trigger
$kill @e[tag=kf.$(node).trigger]
$data remove storage kf_3d_triggers $(node)

$scoreboard players reset .kf_3d_triggers.$(node).single kf_3d_triggers
$scoreboard players reset .kf_3d_triggers.$(node).triggered kf_3d_triggers