# Do not edit this file.


# Kill all entities connected to the trigger
$kill @e[tag=kf.$(id).trigger]
$data remove storage kf_3d_triggers $(id)

$scoreboard players reset .kf_3d_triggers.$(id).single kf_3d_triggers
$scoreboard players reset .kf_3d_triggers.$(id).triggered kf_3d_triggers