# Do not edit this file.


# Toggle the debug
execute if score .kf_3d_triggers.move kf_3d_triggers matches 0 run return run scoreboard players set .kf_3d_triggers.move kf_3d_triggers 1
execute if score .kf_3d_triggers.move kf_3d_triggers matches 1 run return run scoreboard players set .kf_3d_triggers.move kf_3d_triggers 0