# Do not edit this file.


$data modify storage quicksaves input.score set from storage quicksaves $(active_node).data[$(active_id)].score
$data modify storage quicksaves input.value set from storage quicksaves $(active_node).data[$(active_id)].value
$data modify storage quicksaves input.obj set from storage quicksaves $(active_node).data[$(active_id)].obj

$tellraw @a [{"color":"gray","text":"ID: "},{"color":"green","text":"$(print_id) "},{"color":"gray","text":"Score: "},{"color":"green","text":"$(score)"},{"color":"gray","text":" Obj: "},{"color":"green","text":"$(obj)"},{"color":"gray","text":" Value: "},{"color":"green","text":"$(value)"}]

scoreboard players add #quicksave_id quicksave 1
execute store result storage quicksaves input.active_id int 1 run scoreboard players get #quicksave_id quicksave
scoreboard players add #quicksave_print_id quicksave 1
execute store result storage quicksaves input.print_id int 1 run scoreboard players get #quicksave_print_id quicksave

execute unless score #quicksave_id quicksave matches 11.. run function quicksave:private/_print with storage quicksaves input