# Do not edit this file.


$data modify storage quicksaves $(node).data[$(id)].score set value "$(score)"
$data modify storage quicksaves $(node).data[$(id)].obj set value "$(obj)"
$data modify storage quicksaves $(node).data[$(id)].value set value $(value)

$execute store result score #quicksave_temp quicksave run data get storage quicksaves $(node).id
scoreboard players add #quicksave_temp quicksave 1
$execute store result storage quicksaves $(node).id int 1 run scoreboard players get #quicksave_temp quicksave