# Do not edit this file.


$data modify storage quicksaves input.score set from storage quicksaves $(active_node).data[$(active_id)].score
$data modify storage quicksaves input.value set from storage quicksaves $(active_node).data[$(active_id)].value
$data modify storage quicksaves input.obj set from storage quicksaves $(active_node).data[$(active_id)].obj

$scoreboard players set $(score) $(obj) $(value)

scoreboard players add #quicksave_id quicksave 1
execute store result storage quicksaves input.active_id int 1 run scoreboard players get #quicksave_id quicksave

execute unless score #quicksave_id quicksave matches 11.. run function quicksave:private/iterator with storage quicksaves input