# Do not edit this file.


# Unlock all scoreboards for the player
scoreboard players set @s inputs.w_lock 0
scoreboard players set @s inputs.a_lock 0
scoreboard players set @s inputs.s_lock 0
scoreboard players set @s inputs.d_lock 0
scoreboard players set @s inputs.ctrl_lock 0
scoreboard players set @s inputs.shift_lock 0
scoreboard players set @s inputs.space_lock 0

scoreboard players set @s inputs.slot1_lock 0
scoreboard players set @s inputs.slot2_lock 0
scoreboard players set @s inputs.slot3_lock 0
scoreboard players set @s inputs.slot4_lock 0
scoreboard players set @s inputs.slot5_lock 0
scoreboard players set @s inputs.slot6_lock 0
scoreboard players set @s inputs.slot7_lock 0
scoreboard players set @s inputs.slot8_lock 0
scoreboard players set @s inputs.slot9_lock 0