# Do not edit this file.


# Remove data from the storage
data remove storage timers node_list

# Resetting the temporary scores
scoreboard players reset timers.node_list.id timers
scoreboard players reset timers.node_list.size timers