# Do not edit this file.


# If trigger type is 0, run the function to show small trigger block displays
$function modules:timers/delete {node:$(value)}

# Incrementing the dialogue ID
scoreboard players add timers.node_list.id timers 1
execute store result storage timers node_list.active_id int 1 run scoreboard players get timers.node_list.id timers

# Pulling the dialogue data from the storage
$data modify storage timers node_list.value set from storage timers node_list.data[$(active_id)]

# If the dialogue is not iterated through, run the function again
execute unless score timers.node_list.id timers >= timers.node_list.size timers run function modules:timers/private/_delete_all with storage timers node_list

# If the dialogue is iterated through fully, delete the temporary data
execute if score timers.node_list.id timers = timers.node_list.size timers run function modules:timers/private/_clear_temp