# Do not edit this file.


# If more than 10 - set the value as it is
$execute if score timers.$(id).t timers matches 10.. run data modify storage timers timer_display.t set value "$(t)"
$execute if score timers.$(id).s timers matches 10.. run data modify storage timers timer_display.s set value "$(s)"
$execute if score timers.$(id).m timers matches 10.. run data modify storage timers timer_display.m set value "$(m)"
$execute if score timers.$(id).h timers matches 10.. run data modify storage timers timer_display.h set value "$(h)"

# If less than 10 - add another zero to simulate the clock
$execute if score timers.$(id).t timers matches -1 run data modify storage timers timer_display.t set value "00"
$execute if score timers.$(id).t timers matches 0..9 run data modify storage timers timer_display.t set value "0$(t)"
$execute if score timers.$(id).s timers matches ..9 run data modify storage timers timer_display.s set value "0$(s)"
$execute if score timers.$(id).m timers matches ..9 run data modify storage timers timer_display.m set value "0$(m)"
$execute if score timers.$(id).h timers matches ..9 run data modify storage timers timer_display.h set value "0$(h)"

function modules:timers/private/_display with storage timers timer_display