# Do not edit this file.


$data modify storage timers $(id).end_s set value $(value)
$data modify storage timers $(id).init.[].end_s set value $(value)
$execute store result score timers.$(id).end_s timers run data get storage timers $(id).end_s 1