# Do not edit this file.


$data modify storage timers $(id).end_h set value $(value)
$data modify storage timers $(id).init.[].end_h set value $(value)
$execute store result score timers.$(id).end_h timers run data get storage timers $(id).end_h 1