# Do not edit this file.


$data modify storage timers $(id).h set value $(value)
$data modify storage timers $(id).init.[].h set value $(value)
$execute store result score timers.$(id).h timers run data get storage timers $(id).h 1