# Do not edit this file.


$data modify storage timers $(id).t set value $(value)
$data modify storage timers $(id).init.[].t set value $(value)
$execute store result score timers.$(id).t timers run data get storage timers $(id).t 1