# Do not edit this file.


$data modify storage timers $(id).end_t set value $(value)
$data modify storage timers $(id).init.[].end_t set value $(value)
$execute store result score timers.$(id).end_t timers run data get storage timers $(id).end_t 1