# Do not edit this file.


$data modify storage timers $(id).m set value $(value)
$data modify storage timers $(id).init.[].m set value $(value)
$execute store result score timers.$(id).m timers run data get storage timers $(id).m 1