# Do not edit this file.


$data modify storage timers $(id).end_m set value $(value)
$data modify storage timers $(id).init.[].end_m set value $(value)
$execute store result score timers.$(id).end_m timers run data get storage timers $(id).end_m 1